version: 2
jobs:
  checkout_code:
    docker:
      - image: debian:stretch
    steps:
      - checkout
  hello_world:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  say_hoge:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Greeting
          command: echo hoge.
  say_fuga:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Greeting
          command: echo fuga.

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - hello_world:
          requires:
            - checkout_code
      - hold_say_hoge:
          type: approval
          requires:
            - hello_world
      - say_hoge:
          requires:
            - hold_say_hoge
      - hold_say_fuga:
          type: approval
          requires:
            - say_hoge
      - say_fuga:
          requires:
            - hold_say_fuga

