version: 2
jobs:
  checkout_code:
    docker:
      - image: debian:stretch
    steps:
      - checkout
  hello_world:
    docker:
      - image: debian:stretch
    steps:
      - say_hello:
          name: Greeting
          command: echo Hello, world.
      - say_date:
          name: Print the Current Time
          command: date
  say_hoge:
    docker:
      - image: debian:stretch
    steps:
      - say_hoge:
          name: Greeting
          command: echo hoge.
      - say_fuga:
          name: Greeting2
          command: echo fuga.

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - hello_world:
          requires:
            - checkout_code
#      - hold_say_hoge:
#          type: approve
#          requires:
#            - hello_world
